version: '3'
services:
  database:
    image: postgres
    container_name: pgdatabase
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:${DEFAULT_PORT}"
    environment:
      POSTGRES_USER: "${DEFAULT_USER}"
      POSTGRES_PASSWORD: "${DEFAULT_PWD}"
      POSTGRES_DB: "${DEFAULT_DB}"

  backend:
    build: ./backend
    depends_on: 
      - 'database'
    ports: 
      - '8080:8080'
    environment:
      DB_CONNECTION_STRING: "postgres://${DEFAULT_USER}:${DEFAULT_PWD}@host.docker.internal/${DEFAULT_DB}"
    volumes:
      - "${PWD}/backend:/src/app"

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - "${PWD}/frontend:/src/app"
    depends_on: 
      - 'backend'

volumes:
  pgdata: